### ISSUE TITLE
Rating state-on/off icon is not correct

### ISSUE THREAD

**Issue by phuyem** [Morgul/ui-bootstrap4#33]
### Bug description:

Right on your online demo , as well as on my project, state-on/off icon does not take effect, which make the icon always a solid/empty star.

BTW, is there someone working on this project ?

**Comment by Morgul** [comment]
The short answer is "not really". I will merge in community changes and do releases as I have time, but I do zero new development. My work project that needed this is in the process of migrating our Angular code to Vue, so every month there's less and less demand for this.

I would _love_ to give the project over to someone, if they want to maintain it, because I don't have the time to. For now, I do my best with the limited time I've got. :)

**Comment by phuyem** [comment]
Hi Morgul,

I understand your situation as I just read your README more. I bet there are many dev who interest in angular1-bs4 but only you stood up and made things work. You are still a Hero !! 

I also feel why your project is moving to Vue. My small team have a quite large project ( for our scale) in ng1 since 2014. But it started dying since 2016 when angular team declare completely new framework , the love/hype from community decreased quite fast as well. We have been looking for alternative as we are updating our project since 2017, but we don't have the courage and good finance to move to React/Vue/Ng2, so we decided to stick with ng1..... So best of lucks to your migrating project.

As for the issue , if someone in the future read this, here is the solution  : 

Open **ui-bootstrap4\template\rating\rating.html**  and remove this bloc of code 

 `  <svg data-ng-if="$index < value" width="1792" height="1792" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1728 647q0 22-26 48l-363 354 86 500q1 7 1 20 0 21-10.5 35.5t-30.5 14.5q-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"/></svg>
        <svg data-ng-if="$index >= value" width="1792" height="1792" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1201 1004l306-297-422-62-189-382-189 382-422 62 306 297-73 421 378-199 377 199zm527-357q0 22-26 48l-363 354 86 500q1 7 1 20 0 50-41 50-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"/></svg>
`

Issue closed!

**Comment by Morgul** [comment]
@phuyem Yeah, we've been running a hybrid application since 2017, and are hoping to be off angular 1 by 2019. One of the selling points of Vue for us was that it's template language is _very_ similar, and running a hybrid app is pretty trivial; you make the top level app Vue, and then make a vue component that contains your previous angular top level component. That should be a pretty small change, without any breakage in the angular app, and then you just move one small piece at a time. I didn't think it would work, but we're a year into the rewrite and it's been wonderful. If you want any tips, I'd be more than happy to share a gist of what we did to make it all work.

I'll keep this issue open for now; I'd like to actually change this in the source and release a new build... eventually.
