### ISSUE TITLE
DatePickerPopUp Format is not by ISO standards?

### ISSUE THREAD

**Issue by digibum** [Morgul/ui-bootstrap4#51]
Using format string "DD.MM.YYYY" returns
Expected: "19.06.2019".
Current: "DD.06.YYYY".
Is Dateparser not using ISO standards to format date's?

**Comment by digibum** [comment]
I'm using Moment to get localized date format string.
Moment returns "DD.MM.YYYY" for language 'sl' but Dateparser expects "dd.MM.yyyy".
Why is that?

**Comment by Morgul** [comment]
So, I don't have a great answer, since I'm just (barely) maintaining this code base, and didn't write it. However, it looks like angular's dates use `dd` not `DD`:

https://docs.angularjs.org/api/ng/filter/date

Can't seem to find a reason why, but I'll bet `Dateparser` was written to match Angular's `date`.

**Comment by Morgul** [comment]
Marking this as wontfix, because (like the original authors) I feel it's better to be consistent with the underlying framework.

I get the frustration, and would definitely entertain the idea of allowing the behavior to be changed as desired, but for now, I don't have any plans on changing this.
